name: "Test driver"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  driver:
    uses: catie-aq/zephyr_workflows/.github/workflows/driver.yml@driver/dynamic-board-support
    with:
      path: "samples"
      board: "zest_core_nrf5340"

    secrets:
      personal_access_token: ${{ secrets.CI_6TRON_ZEPHYR_RO }}
